### ISSUE TITLE
[FEATURE REQUEST]: Developer icon

### ISSUE THREAD

**Issue by yokoffing** [seirin-blu/Firefox-Halo#3]
Just wanted to say: I greatly enjoy having `firefox_with_classic_blue_and_paw.png` on my Stable build for the new tab page and as a new tab favicon replacement.

If you ever have time to add a paw to the Firefox Developer icon, that would be amazing! (I also run Firefox Developer.)

**Comment by GrosBourrin** [comment]
would like having myself the default favicon (also known as globe icon)  revamped ! is it possible ?

**Comment by seirin-blu** [comment]
If you can send me a link to which one you're taking about, I can do it more likely than not!

**Comment by seirin-blu** [comment]
I just saw the top one. I'll do both when I get home today.

**Comment by GrosBourrin** [comment]
![2020-08-17_02h39_41](https://user-images.githubusercontent.com/40931468/90347830-f87ab780-e032-11ea-82e3-2644af6854ac.png)

This is the default favicon Firefox uses when it can't find any website favicon. on bookmark menus or bookmark toolbar, also displays it in urlbar before the url. i know it can be change website by website in css, but i would like to know if it's possible to change it globally without adding css for each website.
Oh and i like your theme, nice css sheet very clear to understand

**Comment by seirin-blu** [comment]
> Just wanted to say: I greatly enjoy having `firefox_with_classic_blue_and_paw.png` on my Stable build for the new tab page and as a new tab favicon replacement.
> 
> If you ever have time to add a paw to the Firefox Developer icon, that would be amazing! (I also run Firefox Developer.)

I have created a developer version with paw and a halo version. You can find the developer ones [here.](https://github.com/seirin-blu/Firefox70LogoCustomization)

**Comment by seirin-blu** [comment]
@GrosBourrin I've added that into userchrome, but you'll have to manually change it.

**Comment by seirin-blu** [comment]
@yokoffing I actually made a config that's roughly the same as Halo, but is styled for the dev version. It replaces the reds with blue. Let me know if you want it.

**Comment by yokoffing** [comment]
> I have created a developer version with paw and a halo version. You can find the developer ones [here.](https://github.com/seirin-blu/Firefox70LogoCustomization)

Thank you for your work! He looks stunning ;)

> I actually made a config that's roughly the same as Halo, but is styled for the dev version. It replaces the reds with blue. Let me know if you want it.

I'd like to see it! I recall you posting this on Reddit a few days ago, but I can't seem to find your post now.

**Comment by yokoffing** [comment]
What happened to [this page](https://github.com/seirin-blu/Firefox70LogoCustomization)? I cannot find the Developer icon you made.

Didn't you also have the regular Firefox icon (purple globe) with a paw?
